homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.landingpage, name='landingpage'),
    path('login/', views.loginpage, name='loginpage'),
    path('menu/', views.menupage, name='menupage'),
    path('logout/',views.logoutpage, name='logoutpage'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def loginpage(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('homepage:menupage')
	else:
		form = AuthenticationForm()
	return render(request, 'login.html', {'form':form})

def landingpage(request):
	return render(request, 'landing.html')

def menupage(request):
	if request.user.is_authenticated:
		return render(request,'menu.html')
	else:
		return redirect('homepage:loginpage')

def logoutpage(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			logout(request)
	return redirect('homepage:landingpage')

homepage/templates/landing.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<meta charset="UTF-8">
	<title>Story-9 Rifqi</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>

<body>
	<div class="landing-div">
		<h2>Story-9 Rifqi</h2>
		<h1 id="header-text">Ini Landing Page</h1>
		{% if not user.is_authenticated %}
		<a id="login-text" href="{%url 'homepage:loginpage' %}">Klik disini untuk Login</a>
		{% endif %}
		{% if user.is_authenticated %}
		<a id="login-text" href="{%url 'homepage:menupage' %}">Klik disini untuk menuju menu utama</a>
		{% endif %}
	</div>
</body>

homepage/templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<meta charset="UTF-8">
	<title>Story-9 Rifqi</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>

<body>
	<div class="login-div">
		 <h1>Login</h1>
		 <form class="site-form" action="{%url 'homepage:loginpage' %}" method="post">
		 	{% csrf_token %}
		 	<div id="flexbox-container">
		 	{{form.as_p}}
		 	</div>
		 	<input class="btn" type="submit" value="Login">
		 </form>
	 </div>
</body>

homepage/templates/menu.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<meta charset="UTF-8">
	<title>Story-9 Rifqi</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>

<body>
	<div class="menu-div">
		<h3>Story-9 Rifqi</h3>
		{% if user.is_authenticated %}
		<h1>Welcome {{ user.username }}!</h1>
		<form class="logout-link" action="{%url 'homepage:logoutpage' %}" method="post">
			{% csrf_token %}
			<button class="btn-menu" type="submit">Logout</button>
		</form>
		{% endif %}
	</div>
	
</body>